Static_camera:
    fx: 616.1005249
    fy: 615.82617188
    cx: 318.38803101
    cy: 249.23504639

End_effector_camera:
    fx: 607.18261719
    fy: 606.91986084
    cx: 320.85250854
    cy: 243.40284729
